spring:
  # --- DB PROD (IP Statique Template) ---
  r2dbc:
    url: r2dbc:postgresql://168.119.122.86:5432/yowyob 
    username: master
    password: Azerty1234* 

  # --- REDIS PROD (Cluster Template) ---
  data:
    redis:
      password: Azerty1234*
      cluster:
        max-redirects: 3
        nodes:
          - 168.119.122.86:7001
          - 168.119.122.86:7002
          - 168.119.122.86:7003
          - 168.119.122.86:7004
          - 168.119.122.86:7005
          - 168.119.122.86:7006

  # --- KAFKA PROD ---
  kafka:
    bootstrap-servers: 168.119.122.86:9092
    consumer:
      group-id: organisation-group-prod
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


application:
  cors:
    # Autorise ton propre domaine pour que Swagger UI (JS) puisse appeler l'API
    allowed-origins: "https://organization-service.pynfi.com"